# Copyright (c) AGI.__init__. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# MIT_LICENSE file in the root directory of this source tree.
name: ML
channels:
  - default
  - conda-forge
dependencies:
  - pip=22.3.1
  - python=3.10.8
  - numpy
#  - numpy==1.24.2
  - pandas=1.5.3
  - seaborn=0.11.2
  - pip:
      - torch==1.11.0
      - torchvision==0.12.0
      - torchaudio==0.11.0
      - hydra-core==1.1.0
      - hydra-submitit-launcher==1.1.5
      - gym==0.25.1
      - ale-py==0.8.1
      - dm_control==1.0.3
      - gym-super-mario-bros==7.4.0
      - PyOpenGL-accelerate==3.1.6
      - termcolor==1.1.0
      - wandb==0.12.17
      - imageio==2.22.0
      - imageio-ffmpeg==0.4.7
      - einops==0.4.1
      # Only for me
      - cryptography==39.0.1
      - bleak==0.19.5
#   - pexpect
