defaults:
      - _self_
 
environment:   
    env:
        _target_: Datasets.Suites.DMC
suite: dmc
action_repeat: 2
frame_stack: 3
nstep: 3
task_name: finger_turn_easy
train_steps: 1500000
stddev_schedule: 'linear(1.0,0.1,500000)'



