defaults:
      - _self_
    
suite: dmc
action_repeat: 2
frame_stack: 3
nstep: 3
task_name: humanoid_stand
train_steps: 15000000
stddev_schedule: 'linear(1.0,0.1,2000000)'
lr: 8e-5
trunk_dim: 100

    
hydra:
    job:
        env_set:
          # Environment variables for MuJoCo
          MUJOCO_GL: 'egl'