defaults:
      - 500K
      - _self_
    
suite: dmc
action_repeat: 2
frame_stack: 3
nstep: 1
task_name: walker_stand


batch_size: 512
    
hydra:
    job:
        env_set:
          # Environment variables for MuJoCo
          MKL_SERVICE_FORCE_INTEL: '1'
          MUJOCO_GL: 'egl'