Env: Datasets.Suites.SuperMario.SuperMario
suite: SuperMario
task_name: Mario
discrete: true
action_repeat: 4
truncate_episode_steps: 250
nstep: 10
frame_stack: 4
train_steps: 500000
stddev_schedule: 'linear(1.0,0.1,20000)'

# Two augmentations
aug:
  _target_: Utils.Sequential
  _targets_: [RandomShiftsAug, IntensityAug]
  pad: 4
  noise: 0.05
